# Generated by Django 5.0.7 on 2024-09-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='project.png', upload_to='project')),
                ('title', models.CharField(max_length=24)),
                ('desc', models.CharField(max_length=56)),
            ],
        ),
    ]
