# Generated by Django 5.0.7 on 2024-09-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmodel',
            old_name='image',
            new_name='imagehero',
        ),
    ]
