# Generated by Django 5.0.7 on 2024-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portifolio', '0002_rename_image_projectmodel_imagehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='feedback',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='profile',
            field=models.ImageField(default='profile.png', upload_to='profile'),
        ),
    ]
